# Generated by Django 4.2.3 on 2023-07-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fav_movies", "0002_alter_movie_duration_reservation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movie",
            options={"ordering": ["genre"]},
        ),
        migrations.AlterModelOptions(
            name="reservation",
            options={"ordering": ["showtime"]},
        ),
        migrations.AlterModelOptions(
            name="showtime",
            options={"ordering": ["date"]},
        ),
        migrations.AlterField(
            model_name="movie",
            name="duration",
            field=models.IntegerField(),
        ),
    ]
