# Generated by Django 4.2.3 on 2023-07-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fav_movies", "0003_alter_movie_options_alter_reservation_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="showtime",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
