# Generated by Django 4.2.3 on 2023-07-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fav_movies", "0004_showtime_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="showtime",
            name="available_seats",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name="reservation",
            unique_together={("showtime", "seat_number")},
        ),
    ]
