# Generated by Django 4.2.3 on 2023-07-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fav_movies", "0005_alter_showtime_available_seats_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="seat_number",
            field=models.PositiveIntegerField(max_length=10),
        ),
    ]
