# Generated by Django 4.2.3 on 2023-07-08 08:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fav_movies", "0007_alter_reservation_seat_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation",
            options={"ordering": ["showtime__date", "showtime__time"]},
        ),
    ]
