# Generated by Django 4.2.5 on 2023-10-25 14:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fav_movies", "0008_alter_reservation_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="showtime",
            name="active",
        ),
    ]
